package controller;

import entities.AvisJoueur;
import entities.Equipe;
import entities.User;
import esprit.project.tools.MyDB;
import service.IServiceEquipe;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ServiceEquipe implements IServiceEquipe<Equipe> {

    PreparedStatement prepare;
    Connection connection;
    private static ServiceEquipe instance;
    PreparedStatement preparedStatement;

    public ServiceEquipe() {
        connection = MyDB.getInsatnce().getConnection();

    }

    public static ServiceEquipe getInstance() {
        if (instance == null) {
            instance = new ServiceEquipe();
        }
        return instance;
    }


    @Override
    public void ajouter(Equipe av, User us) throws SQLException {
        String req = "INSERT INTO equipe ( nom, image, id_joueur) VALUES (?, ?, ?)";
        PreparedStatement ps = connection.prepareStatement(req, Statement.RETURN_GENERATED_KEYS);

        ps.setString(1, av.getNom());
        ps.setString(2, av.getImage());
        ps.setInt(3, us.getId());

        ps.executeUpdate();

        ResultSet generatedKeys = ps.getGeneratedKeys();
        if (generatedKeys.next()) {
            int autoGeneratedID = generatedKeys.getInt(1);
            av.setId(autoGeneratedID);


            av.setUser(us);


        }
    }

    @Override
    public void modifier(int id, Equipe equipeModifie, int idjoueur) throws SQLException {
        String req = "UPDATE equipe SET nom=?, image=? WHERE id=?";
        PreparedStatement ps = connection.prepareStatement(req);

        ps.setString(1, equipeModifie.getNom());
        ps.setString(2, equipeModifie.getImage());
        ps.setInt(3, id);

        ps.executeUpdate();
    }

    @Override
    public void supprimer(int id) throws SQLException {
        String req = "DELETE FROM equipe WHERE id=?";
        PreparedStatement ps = connection.prepareStatement(req);

        ps.setInt(1, id);

        ps.executeUpdate();
    }

    @Override
    public List<Equipe> recuperer() throws SQLException {
        List<Equipe> equipeList = new ArrayList<>();
        String req = "SELECT equipe.*, User.name FROM equipe JOIN User ON equipe.id_joueur = User.id";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(req)) {

            while (resultSet.next()) {
                int idEquipe = resultSet.getInt("id");
                String nom = resultSet.getString("nom");
                String image = resultSet.getString("image");
                int idJoueur = resultSet.getInt("id_joueur");
                String name = resultSet.getString("name");

                Equipe eq = new Equipe();
                eq.setId(idEquipe);
                eq.setNom(nom);
                eq.setImage(image);

                User user = new User();
                user.setId(idJoueur);
                user.setName(name);
                eq.setUser(user);

                equipeList.add(eq);
            }
        }
        return equipeList;

    }
}